### ISSUE TITLE
XD vs RF for noisified Adridata. Which has the best ROC curve?

### ISSUE THREAD

**Issue by mbaumer** [drphilmarshall/PS1QLS#16]
This list is the order in which other issues should be completed to achieve this overall goal 
* [x] Check if we really need to subtract off means #14 
* [x] Object-orientify code #15 
* [x] Model data as two populations #12 
* [x] Compute actual probabilities drawing priors from simulation #13 
* [x] Use probabilities to make predictions and compare methods!

**Comment by mbaumer** [comment]
Fit ensembles of XD initializations to ensure global max.

**Comment by drphilmarshall** [comment]
Everything working OK?

**Comment by mbaumer** [comment]
The basic functionality to do this is there--I've opened an updated issue ( #19 ) on understanding/optimizing classifier performance.

**Comment by drphilmarshall** [comment]
Good good!
